- name: Ensure fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Deploy fail2ban config
  ansible.builtin.template:
    src: jail.local.j2
    dest: "{{ fail2ban_config_file }}"
    mode: '0644'
  notify: Restart fail2ban
